version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wp_network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - wp_network

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('GRAPHQL_DEBUG', true);
        define('WP_ENVIRONMENT_TYPE', 'local');
    ports:
      - "8080:80"
    volumes:
      - ./docker/wordpress:/var/www/html
      - ./docker/wordpress/plugins:/var/www/html/wp-content/plugins
    networks:
      - wp_network

volumes:
  pg_data:
  mysql_data:

networks:
  wp_network:
    driver: bridge